name: Cache Example

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/mydeps
          key: cache-f993254

      - name: prime-cache-f993254
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
